=== mika-f/SharpX/src/GlobalSyntax.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="RootNode" type="RootNode" />
    <xsd:complexType name="RootNode">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="AbstractNode" type="AbstractNode" />
            <xsd:element name="Node" type="Node" />
        </xsd:choice>
    </xsd:complexType>
    <xsd:complexType name="AbstractNode">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="AbstractNode" type="AbstractNode" />
            <xsd:element name="Node" type="Node" />
            <xsd:element name="Members" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Member" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Kinds" minOccurs="0" maxOccurs="unbounded">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="Kind" type="xsd:string" />
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                </xsd:sequence>
                                <xsd:attribute name="Type" use="required" type="xsd:string" />
                                <xsd:attribute name="Name" use="required" type="xsd:string" />
                                <xsd:attribute name="List" use="optional" type="ListEnum" />
                                <xsd:attribute name="Nullable" use="optional" type="xsd:boolean" />
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
        <xsd:attribute name="Name" use="required" />
    </xsd:complexType>
    <xsd:complexType name="Node">
        <xsd:sequence>
            <xsd:element name="Members" minOccurs="0" maxOccurs="1">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Member" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Kinds" minOccurs="0" maxOccurs="1">
                                        <xsd:complexType>
                                            <xsd:sequence>
                                                <xsd:element name="Kind" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
                                            </xsd:sequence>
                                        </xsd:complexType>
                                    </xsd:element>
                                </xsd:sequence>
                                <xsd:attribute name="Type" use="required" type="xsd:string" />
                                <xsd:attribute name="Name" use="required" type="xsd:string" />
                                <xsd:attribute name="List" use="optional" type="ListEnum"></xsd:attribute>
                                <xsd:attribute name="Nullable" use="optional" type="xsd:boolean" />
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="Name" use="required" type="xsd:string" />
        <xsd:attribute name="Kind" use="required" type="KindUnion" />
    </xsd:complexType>
    <xsd:simpleType name="ListEnum">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Separated" />
            <xsd:enumeration value="Sequenced" />
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="ListOfStrings">
        <xsd:list itemType="xsd:string" />
    </xsd:simpleType>
    <xsd:simpleType name="KindUnion">
        <xsd:union memberTypes="xsd:string ListOfStrings" />
    </xsd:simpleType>
</xsd:schema>

=== mika-f/SharpX/src/ShaderLab/SharpX.ShaderLab/ShaderLab.Syntax.xml
<?xml version="1.0" encoding="utf-8"?>
<RootNode xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../GlobalSyntax.xsd">
    <AbstractNode Name="TypeSyntax">
        <AbstractNode Name="NameSyntax">
            <AbstractNode Name="SimpleNameSyntax">
                <Members>
                    <Member Type="SyntaxTokenInternal" Name="Identifier" />
                </Members>
                <Node Name="IdentifierNameSyntax" Kind="IdentifierName" />
            </AbstractNode>
            <Node Name="QualifiedNameSyntax" Kind="QualifiedName">
                <Members>
                    <Member Type="NameSyntax" Name="Left" />
                    <Member Type="SyntaxTokenInternal" Name="DotToken">
                        <Kinds>
                            <Kind>DotToken</Kind>
                        </Kinds>
                    </Member>
                    <Member Type="SimpleNameSyntax" Name="Right" />
                </Members>
            </Node>
        </AbstractNode>
    </AbstractNode>
    <AbstractNode Name="ExpressionSyntax">
        <Node Name="LiteralExpressionSyntax" Kind="NumericLiteralExpression StringLiteralExpression">
            <Members>
                <Member Type="SyntaxToken" Name="Token">
                    <Kinds>
                        <Kind>NumericLiteralToken</Kind>
                        <Kind>StringLiteralToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
        <Node Name="TextureLiteralExpressionSyntax" Kind="TextureLiteralExpression">
            <Members>
                <Member Type="LiteralExpressionSyntax" Name="Value" />
                <Member Type="SyntaxToken" Name="OpenBraceToken">
                    <Kinds>
                        <Kind>OpenBraceToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="CloseBraceToken">
                    <Kinds>
                        <Kind>CloseBraceToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
    </AbstractNode>
    <AbstractNode Name="BasePassDeclarationSyntax">
        <Members>
            <Member Type="SyntaxToken" Name="Keyword" />
        </Members>
        <Node Name="PassDeclarationSyntax" Kind="PassDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>PassKeyword</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="OpenBraceToken">
                    <Kinds>
                        <Kind>OpenBraceToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="TagsDeclarationSyntax" Name="Tags" Nullable="true" />
                <Member Type="BaseCommandDeclarationSyntax" Name="Commands" List="Sequenced" />
                <Member Type="CgProgramDeclarationSyntax" Name="CgProgram" />
                <Member Type="SyntaxToken" Name="CloseBraceToken">
                    <Kinds>
                        <Kind>CloseBraceToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
        <Node Name="GrabPassDeclarationSyntax" Kind="GrabPassDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>GrabPassKeyword</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="OpenBraceToken">
                    <Kinds>
                        <Kind>OpenBraceToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="Identifier" Nullable="true">
                    <Kinds>
                        <Kind>IdentifierToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="TagsDeclarationSyntax" Name="Tags" Nullable="true" />
                <Member Type="NameDeclarationSyntax" Name="Name" Nullable="true" />
                <Member Type="SyntaxToken" Name="CloseBraceToken">
                    <Kinds>
                        <Kind>CloseBraceToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
        <Node Name="UsePassDeclarationSyntax" Kind="UsePassDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>UsePassKeyword</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="PassReference">
                    <Kinds>
                        <Kind>StringLiteralToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
    </AbstractNode>
    <AbstractNode Name="BaseCommandDeclarationSyntax">
        <Members>
            <Member Type="SyntaxToken" Name="Keyword" />
        </Members>
        <Node Name="CommandDeclarationSyntax" Kind="CommandDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>IdentifierToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="IdentifierNameSyntax" Name="Arguments" List="Separated" />
            </Members>
        </Node>
        <Node Name="StencilDeclarationSyntax" Kind="StencilDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>StencilKeyword</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="OpenBraceToken">
                    <Kinds>
                        <Kind>OpenBraceToken</Kind>
                    </Kinds>
                </Member>
                <Member Type="CommandDeclarationSyntax" Name="Commands" List="Sequenced" />
                <Member Type="SyntaxToken" Name="CloseBraceToken">
                    <Kinds>
                        <Kind>CloseBraceToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
        <Node Name="NameDeclarationSyntax" Kind="NameDeclaration">
            <Members>
                <Member Type="SyntaxToken" Name="Keyword">
                    <Kinds>
                        <Kind>NameKeyword</Kind>
                    </Kinds>
                </Member>
                <Member Type="SyntaxToken" Name="Name">
                    <Kinds>
                        <Kind>StringLiteralToken</Kind>
                    </Kinds>
                </Member>
            </Members>
        </Node>
    </AbstractNode>
    <Node Name="EqualsValueClauseSyntax" Kind="EqualsValueClause">
        <Members>
            <Member Type="SyntaxToken" Name="EqualsToken">
                <Kinds>
                    <Kind>EqualsToken</Kind>
                </Kinds>
            </Member>
            <Member Type="ExpressionSyntax" Name="Value" />
        </Members>
    </Node>
    <Node Name="ArgumentListSyntax" Kind="ArgumentList">
        <Members>
            <Member Type="SyntaxToken" Name="OpenParenToken">
                <Kinds>
                    <Kind>OpenParenToken</Kind>
                </Kinds>
            </Member>
            <Member Type="ArgumentSyntax" Name="Arguments" List="Separated" />
            <Member Type="SyntaxToken" Name="CloseParenToken">
                <Kinds>
                    <Kind>CloseParenToken</Kind>
                </Kinds>
            </Member>
        </Members>
    </Node>
    <Node Name="ArgumentSyntax" Kind="Argument">
        <Members>
            <Member Type="ExpressionSyntax" Name="Expression" />
        </Members>
    </Node>
    <Node Name="AttributeListSyntax" Kind="AttributeList">
        <Members>
            <Member Type="SyntaxToken" Name="OpenBracketToken">
                <Kinds>
                    <Kind>OpenBracketToken</Kind>
                </Kinds>
            </Member>
            <Member Type="AttributeSyntax" Name="Attributes" List="Separated" />
            <Member Type="SyntaxToken" Name="CloseBracketToken">
                <Kinds>
                    <Kind>CloseBracketToken</Kind>
                </Kinds>
            </Member>
        </Members>
    </Node>
    <Node Name="AttributeSyntax" Kind="Attribute">
        <Members>
            <Member Type="NameSyntax" Name="Name" />
            <Member Type="ArgumentListSyntax" Name="ArgumentList" Nullable="true" />
        </Members>
    </Node>
    <Node Name="CompilationUnitSyntax" Kind="CompilationUnit">
        <Members>
            <Member Type="ShaderDeclarationSyntax" Name="ShaderDeclaration" />
            <Member Type="SyntaxToken" Name="EndOfFileToken">
                <Kinds>
                    <Kind>EndOfFileToken</Kind>
                </Kinds>
            </Member>
        </Members>
    </Node>
    <Node Name="ShaderDeclarationSyntax" Kind="ShaderDeclaration">
        <Members>
            <Member Type="SyntaxToken" Name="ShaderKeyword">
                <Kinds>
                    <Kind>ShaderKeyword</Kind>
                </Kinds>
            </Member>
            <Member Type="SyntaxToken" Name="Identifier">
                <Kinds>
                    <Kind>StringLiteralToken</Kind>
                </Kinds>
            </Member>
            <Member Type="SyntaxToken" Name="OpenBraceToken">
                <Kinds>
                    <Kind>OpenBraceToken</Kind>
                </Kinds>
            </Member>
            <Member Type="PropertiesDeclarationSyntax" Name="Properties" Nullable="true" />
            <Member Type="CgIncludeDeclarationSyntax" Name="CgInclude" Nullable="true" />
